#stage 1
FROM node:latest as node
WORKDIR /app
# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH
RUN npm install -g npm@8.13.2
#COPY data/package.json /app/package.json
COPY data /app
RUN npm install --legacy-peer-deps

RUN npm install -g @angular/cli

#CMD ng serve --host 0.0.0.0
ENV PORT 4200
EXPOSE ${PORT}
#CMD [ "ng","serve", "start" ]